name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-11.0

    steps:
      - uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2

      - name: Build monaco
        run: cd Orion/monaco && npm i && npm run build
#       - name: Run tests
#         run: xcodebuild clean test -scheme Orion CODE_SIGNING_REQUIRED=NO
